readthedocs/builds/urls.py
# -*- coding: utf-8 -*-

"""URL configuration for builds app."""
from django.conf.urls import url

from .views import builds_redirect_detail, builds_redirect_list


urlpatterns = [
    url(
        r'^(?P<project_slug>[-\w]+)/(?P<pk>\d+)/$',
        builds_redirect_detail,
        name='old_builds_detail',
    ),
    url(
        r'^(?P<project_slug>[-\w]+)/$',
        builds_redirect_list,
        name='old_builds_project_list',
    ),
]

readthedocs/gold/urls.py
# -*- coding: utf-8 -*-

"""Gold subscription URLs."""

from django.conf.urls import url

from readthedocs.gold import views
from readthedocs.projects.constants import PROJECT_SLUG_REGEX


urlpatterns = [
    url(r'^$', views.DetailGoldSubscription.as_view(), name='gold_detail'),
    url(
        r'^subscription/$',
        views.UpdateGoldSubscription.as_view(),
        name='gold_subscription',
    ),
    url(
        r'^cancel/$',
        views.DeleteGoldSubscription.as_view(),
        name='gold_cancel',
    ),
    url(r'^projects/$', views.projects, name='gold_projects'),
    url(
        (
            r'^projects/remove/(?P<project_slug>{project_slug})/$'.format(
                project_slug=PROJECT_SLUG_REGEX,
            )
        ),
        views.projects_remove,
        name='gold_projects_remove',
    ),
]

readthedocs/notifications/urls.py
# -*- coding: utf-8 -*-

"""Renames for messages_extends URLs."""

from django.conf.urls import url
from messages_extends.views import message_mark_all_read, message_mark_read


urlpatterns = [
    url(
        r'^dismiss/(?P<message_id>\d+)/$',
        message_mark_read,
        name='message_mark_read',
    ),
    url(
        r'^dismiss/all/$',
        message_mark_all_read,
        name='message_mark_all_read',
    ),
]

readthedocs/urls.py
# pylint: disable=missing-docstring
import os
from functools import reduce
from operator import add

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic.base import RedirectView, TemplateView

from readthedocs.core.urls import core_urls, deprecated_urls, docs_urls
from readthedocs.core.views import (
    HomepageView,
    SupportView,
    do_not_track,
    server_error_404,
    server_error_500,
)
from readthedocs.search import views as search_views
from readthedocs.search.api import PageSearchAPIView


admin.autodiscover()

handler404 = server_error_404
handler500 = server_error_500

basic_urls = [
    url(r'^$', HomepageView.as_view(), name='homepage'),
    url(r'^support/', SupportView.as_view(), name='support'),
    url(r'^security/', TemplateView.as_view(template_name='security.html')),
    url(
        r'^\.well-known/security.txt$',
        TemplateView
        .as_view(template_name='security.txt', content_type='text/plain'),
    ),
]

rtd_urls = [
    url(r'^search/$', search_views.elastic_search, name='search'),
    url(r'^dashboard/', include('readthedocs.projects.urls.private')),
    url(r'^profiles/', include('readthedocs.profiles.urls.public')),
    url(r'^accounts/', include('readthedocs.profiles.urls.private')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^notifications/', include('readthedocs.notifications.urls')),
    url(r'^accounts/gold/', include('readthedocs.gold.urls')),
    # For redirects
    url(r'^builds/', include('readthedocs.builds.urls')),
    # For testing the 404's with DEBUG on.
    url(r'^404/$', handler404),
    # For testing the 500's with DEBUG on.
    url(r'^500/$', handler500),
]

project_urls = [
    url(r'^projects/', include('readthedocs.projects.urls.public')),
]

api_urls = [
    url(r'^api/v2/', include('readthedocs.api.v2.urls')),
    # Keep the `doc_search` at root level, so the test does not fail for other API
    url(r'^api/v2/docsearch/$', PageSearchAPIView.as_view(), name='doc_search'),
    url(
        r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework')
    ),
    url(r'^api/v3/', include('readthedocs.api.v3.urls')),
]

i18n_urls = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
]

admin_urls = [
    url(r'^admin/', admin.site.urls),
]

dnt_urls = [
    url(r'^\.well-known/dnt/$', do_not_track),

    # https://github.com/EFForg/dnt-guide#12-how-to-assert-dnt-compliance
    url(
        r'^\.well-known/dnt-policy.txt$',
        TemplateView
        .as_view(template_name='dnt-policy.txt', content_type='text/plain'),
    ),
]

debug_urls = []
for build_format in ('epub', 'htmlzip', 'json', 'pdf'):
    debug_urls += static(
        settings.MEDIA_URL + build_format,
        document_root=os.path.join(settings.MEDIA_ROOT, build_format),
    )
debug_urls += [
    url(
        'style-catalog/$',
        TemplateView.as_view(template_name='style_catalog.html'),
    ),

    # This must come last after the build output files
    url(
        r'^media/(?P<remainder>.+)$',
        RedirectView.as_view(url=settings.STATIC_URL + '%(remainder)s'),
        name='media-redirect',
    ),
]

# Export URLs
groups = [
    basic_urls,
    rtd_urls,
    project_urls,
    api_urls,
    core_urls,
    i18n_urls,
    deprecated_urls,
]

if settings.DO_NOT_TRACK_ENABLED:
    # Include Do Not Track URLs if DNT is supported
    groups.append(dnt_urls)


if settings.READ_THE_DOCS_EXTENSIONS:
    groups.append([
        url(r'^', include('readthedocsext.urls'))
    ])

if not settings.USE_SUBDOMAIN or settings.DEBUG:
    groups.insert(0, docs_urls)
if settings.ALLOW_ADMIN:
    groups.append(admin_urls)
if settings.DEBUG:
    import debug_toolbar

    debug_urls += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]
    groups.append(debug_urls)

urlpatterns = reduce(add, groups)

readthedocs/builds/models.py
"""Models for the builds app."""

import datetime
import logging
import os.path
import re
from shutil import rmtree

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext
from django.utils.translation import ugettext_lazy as _
from django_extensions.db.models import TimeStampedModel
from jsonfield import JSONField
from polymorphic.models import PolymorphicModel

import readthedocs.builds.automation_actions as actions
from readthedocs.config import LATEST_CONFIGURATION_VERSION
from readthedocs.core.utils import broadcast
from readthedocs.projects.constants import (
    BITBUCKET_COMMIT_URL,
    BITBUCKET_URL,
    GITHUB_BRAND,
    GITHUB_COMMIT_URL,
    GITHUB_URL,
    GITHUB_PULL_REQUEST_URL,
    GITHUB_PULL_REQUEST_COMMIT_URL,
    GITLAB_BRAND,
    GITLAB_COMMIT_URL,
    GITLAB_MERGE_REQUEST_URL,
    GITLAB_MERGE_REQUEST_COMMIT_URL,
    GITLAB_URL,
    PRIVACY_CHOICES,
    PRIVATE,
    MEDIA_TYPES,
)
from readthedocs.projects.models import APIProject, Project
from readthedocs.projects.version_handling import determine_stable_version

from readthedocs.builds.constants import (
    BRANCH,
    BUILD_STATE,
    BUILD_STATE_FINISHED,
    BUILD_STATE_TRIGGERED,
    BUILD_TYPES,
    GENERIC_EXTERNAL_VERSION_NAME,
    GITHUB_EXTERNAL_VERSION_NAME,
    GITLAB_EXTERNAL_VERSION_NAME,
    INTERNAL,
    LATEST,
    NON_REPOSITORY_VERSIONS,
    EXTERNAL,
    STABLE,
    TAG,
    VERSION_TYPES,
)
from readthedocs.builds.managers import (
    VersionManager,
    InternalVersionManager,
    ExternalVersionManager,
    BuildManager,
    InternalBuildManager,
    ExternalBuildManager,
)
from readthedocs.builds.querysets import (
    BuildQuerySet,
    RelatedBuildQuerySet,
    VersionQuerySet,
)
from readthedocs.builds.utils import (
    get_bitbucket_username_repo,
    get_github_username_repo,
    get_gitlab_username_repo,
)
from readthedocs.builds.version_slug import VersionSlugField
from readthedocs.oauth.models import RemoteRepository


log = logging.getLogger(__name__)


class Version(models.Model):

    """Version of a ``Project``."""

    project = models.ForeignKey(
        Project,
        verbose_name=_('Project'),
        related_name='versions',
    )
    type = models.CharField(
        _('Type'),
        max_length=20,
        choices=VERSION_TYPES,
        default='unknown',
    )
    # used by the vcs backend

    #: The identifier is the ID for the revision this is version is for. This
    #: might be the revision number (e.g. in SVN), or the commit hash (e.g. in
    #: Git). If the this version is pointing to a branch, then ``identifier``
    #: will contain the branch name.
    identifier = models.CharField(_('Identifier'), max_length=255)

    #: This is the actual name that we got for the commit stored in
    #: ``identifier``. This might be the tag or branch name like ``"v1.0.4"``.
    #: However this might also hold special version names like ``"latest"``
    #: and ``"stable"``.
    verbose_name = models.CharField(_('Verbose Name'), max_length=255)

    #: The slug is the slugified version of ``verbose_name`` that can be used
    #: in the URL to identify this version in a project. It's also used in the
    #: filesystem to determine how the paths for this version are called. It
    #: must not be used for any other identifying purposes.
    slug = VersionSlugField(
        _('Slug'),
        max_length=255,
        populate_from='verbose_name',
    )

    supported = models.BooleanField(_('Supported'), default=True)
    active = models.BooleanField(_('Active'), default=False)
    built = models.BooleanField(_('Built'), default=False)
    uploaded = models.BooleanField(_('Uploaded'), default=False)
    privacy_level = models.CharField(
        _('Privacy Level'),
        max_length=20,
        choices=PRIVACY_CHOICES,
        default=settings.DEFAULT_VERSION_PRIVACY_LEVEL,
        help_text=_('Level of privacy for this Version.'),
    )
    machine = models.BooleanField(_('Machine Created'), default=False)

    objects = VersionManager.from_queryset(VersionQuerySet)()
    # Only include BRANCH, TAG, UNKNOWN type Versions.
    internal = InternalVersionManager.from_queryset(VersionQuerySet)()
    # Only include EXTERNAL type Versions.
    external = ExternalVersionManager.from_queryset(VersionQuerySet)()

    class Meta:
        unique_together = [('project', 'slug')]
        ordering = ['-verbose_name']
        permissions = (
            # Translators: Permission around whether a user can view the
            #              version
            ('view_version', _('View Version')),
        )

    def __str__(self):
        return ugettext(
            'Version {version} of {project} ({pk})'.format(
                version=self.verbose_name,
                project=self.project,
                pk=self.pk,
            ),
        )

    @property
    def ref(self):
        if self.slug == STABLE:
            stable = determine_stable_version(
                self.project.versions(manager=INTERNAL).all()
            )
            if stable:
                return stable.slug

    @property
    def vcs_url(self):
        """
        Generate VCS (github, gitlab, bitbucket) URL for this version.

        Example: https://github.com/rtfd/readthedocs.org/tree/3.4.2/.
        External Version Example: https://github.com/rtfd/readthedocs.org/pull/99/.
        """
        if self.type == EXTERNAL:
            if 'github' in self.project.repo:
                user, repo = get_github_username_repo(self.project.repo)
                return GITHUB_PULL_REQUEST_URL.format(
                    user=user,
                    repo=repo,
                    number=self.verbose_name,
                )
            if 'gitlab' in self.project.repo:
                user, repo = get_gitlab_username_repo(self.project.repo)
                return GITLAB_MERGE_REQUEST_URL.format(
                    user=user,
                    repo=repo,
                    number=self.verbose_name,
                )
            # TODO: Add VCS URL for BitBucket.
            return ''

        url = ''
        if self.slug == STABLE:
            slug_url = self.ref
        elif self.slug == LATEST:
            slug_url = self.project.default_branch or self.project.vcs_repo().fallback_branch
        else:
            slug_url = self.slug

        if ('github' in self.project.repo) or ('gitlab' in self.project.repo):
            url = f'/tree/{slug_url}/'

        if 'bitbucket' in self.project.repo:
            slug_url = self.identifier
            url = f'/src/{slug_url}'

        # TODO: improve this replacing
        return self.project.repo.replace('git://', 'https://').replace('.git', '') + url

    @property
    def last_build(self):
        return self.builds.order_by('-date').first()

    @property
    def config(self):
        """
        Proxy to the configuration of the build.

        :returns: The configuration used in the last successful build.
        :rtype: dict
        """
        last_build = (
            self.builds(manager=INTERNAL).filter(
                state=BUILD_STATE_FINISHED,
                success=True,
            ).order_by('-date')
            .only('_config')
            .first()
        )
        return last_build.config

    @property
    def commit_name(self):
        """
        Return the branch name, the tag name or the revision identifier.

        The result could be used as ref in a git repo, e.g. for linking to
        GitHub, Bitbucket or GitLab.
        """
        # LATEST is special as it is usually a branch but does not contain the
        # name in verbose_name.
        if self.slug == LATEST:
            if self.project.default_branch:
                return self.project.default_branch
            return self.project.vcs_repo().fallback_branch

        if self.slug == STABLE:
            if self.type == BRANCH:
                # Special case, as we do not store the original branch name
                # that the stable version works on. We can only interpolate the
                # name from the commit identifier, but it's hacky.
                # TODO: Refactor ``Version`` to store more actual info about
                # the underlying commits.
                if self.identifier.startswith('origin/'):
                    return self.identifier[len('origin/'):]
            return self.identifier

        # By now we must have handled all special versions.
        if self.slug in NON_REPOSITORY_VERSIONS:
            raise Exception('All special versions must be handled by now.')

        if self.type in (BRANCH, TAG):
            # If this version is a branch or a tag, the verbose_name will
            # contain the actual name. We cannot use identifier as this might
            # include the "origin/..." part in the case of a branch. A tag
            # would contain the hash in identifier, which is not as pretty as
            # the actual tag name.
            return self.verbose_name

        if self.type == EXTERNAL:
            # If this version is a EXTERNAL version, the identifier will
            # contain the actual commit hash. which we can use to
            # generate url for a given file name
            return self.identifier

        # If we came that far it's not a special version
        # nor a branch, tag or EXTERNAL version.
        # Therefore just return the identifier to make a safe guess.
        log.debug(
            'TODO: Raise an exception here. Testing what cases it happens',
        )
        return self.identifier

    def get_absolute_url(self):
        # Hack external versions for now.
        # TODO: We can integrate them into the resolver
        # but this is much simpler to handle since we only link them a couple places for now
        if self.type == EXTERNAL:

readthedocs/api/v2/views/core_views.py
"""Utility endpoints relating to canonical urls, embedded content, etc."""

from django.shortcuts import get_object_or_404
from rest_framework import decorators, permissions, status
from rest_framework.renderers import JSONRenderer
from rest_framework.response import Response

from readthedocs.builds.constants import LATEST
from readthedocs.builds.models import Version
from readthedocs.core.templatetags.core_tags import make_document_url
from readthedocs.projects.models import Project


@decorators.api_view(['GET'])
@decorators.permission_classes((permissions.AllowAny,))
@decorators.renderer_classes((JSONRenderer,))
def docurl(request):
    """
    Get the url that a slug resolves to.

    Example::

        GET https://readthedocs.org/api/v2/docurl/?project=requests&version=latest&doc=index
    """
    project = request.GET.get('project')
    version = request.GET.get('version', LATEST)
    doc = request.GET.get('doc', 'index')
    if project is None:
        return Response(
            {'error': 'Need project and doc'},
            status=status.HTTP_400_BAD_REQUEST,
        )

    project = get_object_or_404(Project, slug=project)
    version = get_object_or_404(
        Version.objects
        .public(request.user, project=project, only_active=False),
        slug=version,
    )
    return Response({
        'url': make_document_url(
            project=project,
            version=version.slug,
            page=doc,
        ),
    })

readthedocs/templates/core/build_list_detailed.html
{% load i18n %}
{% load static %}

          {% for build in build_qs %}
          <li class="module-item col-span">
            <div id="build-{{ build.id }}">
                <a href="{{ build.get_absolute_url }}">{% if build.is_stale %}<span class="icon-warning" title="{% trans 'This build is still waiting to be built' %}"></span>{% endif %}<span id="build-state">{% if build.state != 'finished' %}{{ build.get_state_display }} {% else %} {% if build.success %}{% trans "Passed" %}{% else %}{% trans "Failed" %}{% endif %}{% endif %}</span>
                  <img src="{% static 'core/img/loader.gif' %}" class="build-loading hide">
              <span class="quiet">{% if build.version %}{% if build.is_external %}{% blocktrans with build.external_version_name as external_version_name %}{{ external_version_name }} {% endblocktrans %}{% endif %}{% blocktrans with build.version.slug as slug and build.type as type %}version {{ slug }} ({{ type }}){% endblocktrans %}{% endif %}</span><span class="quiet right">{% blocktrans with build.date|timesince as date %}{{ date }} ago{% endblocktrans %}</span>
              </a>
            </div>
            </li>
          {% empty %}
            <li class="module-item quiet">{% trans "No builds found" %}</li>
          {% endfor %}

readthedocs/templates/core/filter_bar.html
{% load i18n %}

    <!-- BEGIN project bar -->
    <div id="project_bar">
      <div class="wrapper">

        <div class="project-title">
          <h1>{% trans "Filter" %}</h1>
        </div>

        <div class="options">


          <ul>
            {% block filter_bar %}{% endblock %}
          </ul>
        </div>


      </div>
    </div>
    <!-- END project bar -->

readthedocs/templates/core/filter_list.html
{% load i18n %}

        {% for obj in filter.qs %}
        <li class="module-item col-span">
            <div id="obj-{{ obj.id }}">
                <a href="{{ obj.get_absolute_url }}">
                    {{ obj }}
              </a>
            </div>
        </li>
        {% empty %}
        <li class="module-item quiet">{% trans "No objects found" %}</li>
        {% endfor %}

readthedocs/templates/core/header.html
{% load i18n %}
{% load gravatar %}

<!-- BEGIN header-->
<div id="rtfd-header">
  <div class="wrapper">

    <!-- BEGIN header title-->
    <div class="rtfd-header-title">
      <h1>
        {% comment %}Translators: Name of the website{% endcomment %}
        <a href="{% url "homepage" %}">Read the Docs</a>
      </h1>
    </div>
    <!-- END header title -->

    <!-- BEGIN header nav -->
    {% if request.user.is_authenticated %}
    <div class="menu menu-user" id="subnav-user-menu">
      <div class="menu-button">
        <a href="{% url 'projects_dashboard' %}">
          {% gravatar request.user.email 24 %}
          {{ request.user }}</a>
        <button class="menu-drop">▼</button>
      </div>
      <div class="menu-dropdown">
        <ul>
          <li><a href="{% url 'projects_dashboard' %}">{% trans "My Projects" %}</a></li>
          <li><a href="{% url 'profiles_profile_edit' %}">{% trans "Settings" %}</a></li>
          <li><a href="{% url 'support' %}">{% trans "Support" %}</a></li>
        </ul>
        <ul>
          <li><a href="{% url 'account_logout' %}">{% trans "Log Out" %}</a></li>
        </ul>
      </div>
    </div>
    {% else %}
      {% url 'account_login' as login %}
      {% if not request.path == login %}
      <div class="rtfd-header-nav">
        <ul><li><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li></ul>
      </div>
      {% endif %}
    {% endif %}
    <!-- END header nav -->


  </div>
</div>
<!-- END header-->

readthedocs/templates/core/home-header.html
{% load i18n %}

    <!-- BEGIN header-->
    <div id="home-header">
      <div class="wrapper">

        <!-- BEGIN header title-->
        <div class="home-header-title">
          <h1>Read the Docs</h1>
          <p class="tagline">{% trans "Create, host, and browse documentation." %}</p>
        </div>
        <!-- END header title -->

        <!-- BEGIN header links-->
        <div class="home-header-links">
          {% comment %}Translators: Note, the full sentence goes 'Sign up' 'or' 'Log in'. But unfortunately the three bits have to be separate.{% endcomment %}
          <a class="reg" href="{% url "account_signup" %}">{% trans "Sign up" %}</a>
          <div class="login-box">
            <p>{% trans "or" %} <a class="login" href="{% url "account_login" %}">{% trans "Log in" %}</a></p>
          </div>
        </div>
        <!-- END header links -->

      </div>
    </div>
    <!-- END header-->

readthedocs/templates/core/project_detail_right.html
{% load i18n %}
{% load core_tags %}
{% load privacy_tags %}
{% load gravatar %}
{% load projects_tags %}

{% block repo %}
  {% if project.repo %}
    <h3>{% trans "Repository" %}</h3>
    <p class="detail-long">
      {% if project.repo|slice:':4' == 'http' %}
        {{ project.repo|urlize }}
      {% else %}
        {{ project.repo }}
      {% endif %}
    </p>
  {% endif %}
{% endblock %}

{% block slug %}
  {% trans "Used in URL's and in code to represent the project name" as title %}
  <h3 title="{{ title }}">{% trans "Project Slug" %}</h3>
  <p title="{{ title }}" class="detail-long">
      {{ project.slug }}
  </p>
{% endblock %}

{% block last-built %}
  <h3>{% trans "Last Built" %}</h3>
  <p>
    {% with build=project.get_latest_build %}
      {% if build %}
          {% if build.date %}
            {{ build.date|timesince }} ago
            {% if build.success %}
              <span class="build-state build-state-passing">{% trans "passed" %}</span>
            {% else %}
              <span class="build-state build-state-failing">{% trans "failed" %}</span>
            {% endif %}
          {% else %}
            {% trans "Currently Building" %}
          {% endif %}
      {% else %}
        {% trans "No builds yet" %}
      {% endif %}
    {% endwith %}
  </p>
{% endblock %}

{% block owners %}
    <h3>{% trans "Maintainers" %}</h3>
    <p>
      {% for user in project.users.all %}
      <a href="{% url "profiles_profile_detail" user.username %}">{% gravatar user.email 32 %}</a>
      {% endfor %}
    </p>
{% endblock %}

{% block homepage %}
  {% if project.project_url %}
    <h3>{% trans "Home Page" %}</h3>
    <p>
      <a href="{{ project.project_url }}" rel="nofollow,noindex">{{ project.project_url }}</a>
    </p>
  {% endif %}
{% endblock %}

{% block badge %}
    <h3>{% trans "Badge" %}</h3>
      <img src="{{ badge_url }}" />
      <a href="{{ site_url }}" style="text-decoration: none;" onclick="$('#badge_markup').toggle(); return false;">
        <span class="badge-info" title="Get this badge"></span> 
      </a>
      {% include "core/badge_markup.html" with badge_url=badge_url site_url=site_url %}
{% endblock %}


{% block tags %}
    <h3>{% trans "Tags" %}</h3>
    <p>

    {% if project.tags.exists %}
        {% for tag in project.tags.all %}
          <a href="{% url "projects_tag_detail" tag.slug %}">{{ tag.name }}</a>{% if forloop.last %}{% else %}, {% endif %}
        {% endfor %}
    {% else %}
      {% trans "Project has no tags." %}
      {% if request.user|is_admin:project %}

        {% url 'projects_edit' project.slug as edit_url %}
          {% blocktrans trimmed %}
          Add some in your <a href="{{ edit_url }}">project settings</a>.
          {% endblocktrans %}
      {% endif %}
    {% endif %}

    </p>
{% endblock %}

{% block privacy-level %}
  <h3>{% trans "Project Privacy Level" %}</h3>
  <div id="privacy_level">
    <p>
      {{ project.get_privacy_level_display }}
    </p>
  </div>
{% endblock %}

{% block short-urls %}
  <h3>{% trans "Short URLs" %}</h3>
  <p>
    <a href="http://{{ project.slug}}.{{ PUBLIC_DOMAIN }}">{{ project.slug }}.{{ PUBLIC_DOMAIN }}</a><br>
    {% if PUBLIC_DOMAIN == "readthedocs.io" %}
    <a href="http://{{ project.slug}}.rtfd.io">{{ project.slug }}.rtfd.io</a>
    {% endif %}
  </p>
{% endblock %}

{% block translations %}
  {% if project.translations.exists %}
    <h3>{% trans "Translations" %}</h3>
      <ul>
      {% for trans in project.translations.all %}
          <li><a href="{{ trans.get_docs_url }}">{{ trans.language }}</a></li>
      {% endfor %}
      </ul>
  {% endif %}
{% endblock %}

{% block subprojects %}
  {% if project.subprojects.exists %}
    <h3>{% trans "Sub Projects" %}</h3>
      <ul>
      {% for rel in project.subprojects.all %}
          <li><a href="{{ rel.get_absolute_url }}">{{ rel.child }}</a></li>
      {% endfor %}
      </ul>
  {% endif %}
{% endblock %}

{% block defaults %}
<h3>{% trans "Default Version" %}</h3>
<p> {{ project.get_default_version }}</p>

<h3>{% trans "'latest' Version" %}</h3>
<p> {{ project.get_default_branch }}</p>
{% endblock %}

readthedocs/templates/core/project_details.html
{% load i18n %}
{% load core_tags %}
{% load privacy_tags %}
{% load gravatar %}
{% load projects_tags %}

<div id="project_details">
  <div class="wrapper">

<div class="module">
  {% if onboard %}
  <!-- BEGIN onboard -->
    {% include 'projects/onboard_detail.html' %}
  <!-- END onboard -->
  {% endif %}


  <div class="module-header">
    <h3>{% trans "Versions" %}</h3>
  </div>

  <div class="module-list">

    <div class="module-list-wrapper">
      <ul>
      {% for version in versions|sort_version_aware %}
        <li class="module-item col-span">
        {% if version.uploaded or version.built %}
          {# Link to the docs #}
          <a class="module-item-title" href="{{ version.get_absolute_url }}">
            {{ version.slug }}
          {% if request.user in project.users.all %}
            <span class="right-menu quiet">{{ version.get_privacy_level_display }}</span>
          {% endif %}
          </a>
        {% else %}
          <a class="module-item-title" href="{{ version.project.get_builds_url }}">
            {{ version.slug }}
          </a>
        {% endif %}
          {% if request.user|is_admin:project %}
            <ul class="module-item-menu">
              <li><a href="{% url "project_version_detail" project.slug version.slug %}">{% trans "Edit" %}</a></li>
            </ul>
          {% endif %}
        </li>

      {% empty %}
        <li class="module-item">
          <p class="quiet">
            {% trans "No active versions." %}
          </p>
        </li>
      {% endfor %}
      </ul>
    </div>
  </div>

{% block build_versions %}
{% if versions and request.user|is_admin:project %}
  <div class="build_a_version">
    <h3>{% trans "Build a version" %}</h3>
    <div class="version_right">
      <form method="post" action="{% url "projects_detail" project.slug %}">
        {% csrf_token %}
        <select id="id_version" name="version_slug">
        {% for version in versions|sort_version_aware %}
          <option value="{{ version.slug }}">{{ version.slug }}</option>
        {% endfor %}
        </select>
        <input type="submit" value="{% trans "Build version" context "Build is a verb" %}">
      </form>
    </div>
  </div>
{% endif %}
{% endblock %}

{% if project.description %}
<div id="project_description">
  <h3>{% trans "Description" %}</h3>
  <p>
    {{ project.description|restructuredtext }}
  </p>
</div>
{% endif %}

</div>{# END .module #}

<div class="project_details">
  {% include "core/project_detail_right.html" with badge_url=badge_url site_url=site_url %}
</div>{# END .project_details #}

  </div>
</div>